[package]
name = "user"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
nix = { version = "0.30", features = ["ioctl"] }

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "bench"
harness = false
